/*
 * dictionary.js — the community-editable heart of Lingo Bridge.
 *
 * Every entry:
 *   term     canonical spelling (lowercase)
 *   variants alternate spellings/forms that should match the same entry
 *   pos      part of speech (n., v., adj., adv., interj., phrase)
 *   gloss    SHORT plain-English substitution used in translations
 *   def      fuller definition, written neutrally and respectfully
 *   example  a real-feeling usage example
 *   origin   where the term is rooted (credit matters — see README)
 *   tags     for filtering: praise, money, people, feelings, internet, uk, ny, bay, dated...
 *
 * House rules for contributions (see CONTRIBUTING section of README):
 *   1. Define, don't mock. Write definitions the way a good dictionary would.
 *   2. Credit origins. Most of this vocabulary comes from AAVE and from
 *      specific communities and regions; say so.
 *   3. No slurs, no terms whose primary use is demeaning a group.
 *   4. Keep glosses short — they get substituted into sentences.
 */

const DICTIONARY = [
  // ---- agreement, truth & emphasis ----
  { term: "no cap", variants: ["nocap"], pos: "phrase", gloss: "no lie", def: "Truthfully; without exaggeration. 'Cap' means a lie or exaggeration, so 'no cap' asserts sincerity.", example: "That was the best meal I've had all year, no cap.", origin: "AAVE / Atlanta hip-hop", tags: ["truth"] },
  { term: "cap", variants: ["capping", "cappin"], pos: "n./v.", gloss: "a lie / lying", def: "A lie or exaggeration; to cap is to lie. Often typed as the blue-cap emoji.", example: "He said he benches 300 — that's cap.", origin: "AAVE", tags: ["truth"] },
  { term: "deadass", variants: ["dead ass"], pos: "adv.", gloss: "seriously", def: "Completely serious; for real. Both an intensifier and a one-word question ('Deadass?').", example: "I'm deadass thinking about moving to Chicago.", origin: "New York, AAVE", tags: ["truth", "ny"] },
  { term: "on god", variants: ["on gawd", "ong"], pos: "phrase", gloss: "I swear", def: "An oath of sincerity; emphasizes that the speaker is telling the truth.", example: "On god, I studied all night for that exam.", origin: "AAVE", tags: ["truth"] },
  { term: "bet", variants: [], pos: "interj.", gloss: "okay, deal", def: "Agreement or confirmation — 'sounds good', 'it's settled'. Can also carry a challenge ('watch me').", example: "'Pick you up at 8?' 'Bet.'", origin: "AAVE", tags: ["agreement"] },
  { term: "say less", variants: ["sayless"], pos: "phrase", gloss: "understood, no need to explain", def: "I'm already on board; you don't need to say anything more.", example: "'Free food at the meeting.' 'Say less.'", origin: "AAVE / hip-hop", tags: ["agreement"] },
  { term: "straight up", variants: [], pos: "adv.", gloss: "honestly", def: "Honestly, directly, without qualification. Also used to agree emphatically.", example: "Straight up, that movie changed how I think.", origin: "AAVE (widespread since the '80s–'90s)", tags: ["truth"] },
  { term: "facts", variants: ["fax", "big facts"], pos: "interj.", gloss: "that's true", def: "Emphatic agreement — what you said is undeniably true.", example: "'Rent is way too high here.' 'Facts.'", origin: "AAVE / internet", tags: ["agreement", "internet"] },
  { term: "periodt", variants: ["period"], pos: "interj.", gloss: "end of discussion", def: "Adds finality to a statement; nothing more needs to be said. The '-t' spelling adds emphasis.", example: "She's the best on the team, periodt.", origin: "AAVE, popularized by Black LGBTQ+ communities", tags: ["emphasis"] },
  { term: "lowkey", variants: ["low key", "low-key"], pos: "adv.", gloss: "somewhat / secretly", def: "Quietly, moderately, or in a way one doesn't want to fully admit.", example: "I lowkey miss my old neighborhood.", origin: "AAVE", tags: ["feelings"] },
  { term: "highkey", variants: ["high key", "high-key"], pos: "adv.", gloss: "openly / very much", def: "The opposite of lowkey: openly, obviously, or intensely.", example: "I highkey need a vacation.", origin: "AAVE (by analogy with lowkey)", tags: ["feelings"] },
  { term: "finna", variants: ["fin to", "finta"], pos: "v.", gloss: "about to", def: "Contraction of 'fixing to' — about to do something.", example: "I'm finna head out in five minutes.", origin: "Southern US / AAVE", tags: ["grammar"] },
  { term: "tryna", variants: [], pos: "v.", gloss: "trying to", def: "Contraction of 'trying to'; often signals intent or an invitation ('you tryna...?').", example: "You tryna get food after this?", origin: "AAVE / casual American English", tags: ["grammar"] },
  { term: "od", variants: ["o.d.", "odee"], pos: "adv./adj.", gloss: "excessively", def: "Over-doing it; too much, extremely. From 'overdose' but used generally.", example: "It's od cold outside today.", origin: "New York", tags: ["ny", "emphasis"] },
  { term: "mad", variants: [], pos: "adv.", gloss: "very / a lot of", def: "An intensifier meaning 'very' or 'a lot of' — not anger.", example: "There were mad people at the park.", origin: "New York, AAVE", tags: ["ny", "emphasis"] },
  { term: "hella", variants: [], pos: "adv.", gloss: "very / a lot of", def: "Intensifier meaning 'very' or 'a lot of'.", example: "That hike was hella long.", origin: "Bay Area, California", tags: ["bay", "emphasis"] },

  // ---- praise & quality ----
  { term: "fire", variants: ["🔥"], pos: "adj.", gloss: "excellent", def: "Extremely good, impressive, stylish.", example: "Her new track is fire.", origin: "AAVE / hip-hop", tags: ["praise"] },
  { term: "lit", variants: [], pos: "adj.", gloss: "exciting / excellent", def: "Exciting, excellent, full of energy — especially events.", example: "The block party was lit last night.", origin: "AAVE (older sense: intoxicated)", tags: ["praise"] },
  { term: "slaps", variants: ["slap", "slapped"], pos: "v.", gloss: "is excellent", def: "Said of music or food that is exceptionally good.", example: "This playlist slaps.", origin: "Bay Area / AAVE", tags: ["praise", "bay"] },
  { term: "bussin", variants: ["bussin'", "bussing"], pos: "adj.", gloss: "delicious / excellent", def: "Extremely good — most often food.", example: "These tacos are bussin.", origin: "AAVE", tags: ["praise", "food"] },
  { term: "goated", variants: [], pos: "adj.", gloss: "the greatest", def: "Having GOAT status — the greatest of all time at something.", example: "That defensive play was goated.", origin: "Internet / sports culture, from GOAT", tags: ["praise", "internet"] },
  { term: "goat", variants: ["g.o.a.t.", "the goat"], pos: "n.", gloss: "greatest of all time", def: "Acronym: Greatest Of All Time. Popularized in hip-hop (LL Cool J's 2000 album 'G.O.A.T.') and sports.", example: "Serena is the GOAT, and it's not close.", origin: "Hip-hop / sports", tags: ["praise"] },
  { term: "hits different", variants: ["hit different"], pos: "phrase", gloss: "is uniquely good", def: "Affects you in a special way; better or more meaningful than the usual version.", example: "Coffee on a rainy morning hits different.", origin: "AAVE / internet", tags: ["praise", "internet"] },
  { term: "banger", variants: ["bangers"], pos: "n.", gloss: "a great song", def: "An outstanding, high-energy song. Extended to anything excellent ('tweet was a banger').", example: "Every song on that album is a banger.", origin: "Hip-hop / club culture", tags: ["praise", "music"] },
  { term: "bop", variants: [], pos: "n.", gloss: "a catchy song", def: "A very catchy, enjoyable song.", example: "This is such a summer bop.", origin: "AAVE / pop-music internet", tags: ["praise", "music"] },
  { term: "ate", variants: ["ate that", "devoured"], pos: "v.", gloss: "performed flawlessly", def: "Did something so well there's nothing left to criticize — 'left no crumbs'.", example: "She ate that presentation.", origin: "AAVE / ballroom culture", tags: ["praise"] },
  { term: "slay", variants: ["slayed"], pos: "v./interj.", gloss: "do it excellently", def: "To succeed impressively or look spectacular; also an exclamation of support.", example: "You got the job? Slay.", origin: "Ballroom culture / Black LGBTQ+ communities", tags: ["praise"] },
  { term: "understood the assignment", variants: ["understand the assignment"], pos: "phrase", gloss: "did exactly what was needed", def: "Fully grasped what a situation called for and delivered it.", example: "Whoever catered this event understood the assignment.", origin: "Internet / AAVE", tags: ["praise", "internet"] },
  { term: "sauce", variants: ["got the sauce"], pos: "n.", gloss: "style, charisma", def: "Effortless style and confidence; also insider skill or know-how ('share the sauce').", example: "You can't teach that kind of sauce.", origin: "AAVE / hip-hop", tags: ["praise", "style"] },
  { term: "drip", variants: ["drippy"], pos: "n.", gloss: "stylish clothes", def: "Fashionable clothing and accessories; a stylish look.", example: "Check the drip — new fit for the show.", origin: "AAVE / Atlanta hip-hop", tags: ["style"] },
  { term: "fit", variants: ["fit check", "fitted"], pos: "n.", gloss: "outfit", def: "Short for outfit. A 'fit check' shows off what you're wearing; 'fitted' means well-dressed.", example: "That's a clean fit for the interview.", origin: "AAVE", tags: ["style"] },
  { term: "kicks", variants: [], pos: "n.", gloss: "shoes", def: "Shoes, especially sneakers.", example: "Fresh kicks — where'd you get them?", origin: "AAVE (long-established)", tags: ["style"] },
  { term: "clean", variants: [], pos: "adj.", gloss: "sharp-looking", def: "Neat, sharp, aesthetically excellent.", example: "That car is clean.", origin: "AAVE / general American", tags: ["praise", "style"] },
  { term: "wavy", variants: [], pos: "adj.", gloss: "stylish / excellent", def: "Cool, stylish, smooth.", example: "That jacket is wavy.", origin: "New York hip-hop (popularized by Max B)", tags: ["praise", "ny"] },
  { term: "gas", variants: ["gassed"], pos: "n./v.", gloss: "excellent / to hype up", def: "As a noun: something excellent. To 'gas someone up' is to hype or over-praise them; 'gassed' means overly hyped or full of yourself.", example: "Stop gassing me up, I only ran one mile.", origin: "AAVE", tags: ["praise"] },
  { term: "mid", variants: [], pos: "adj.", gloss: "mediocre", def: "Average at best; unimpressive. A dismissive rating.", example: "The sequel was mid, honestly.", origin: "Internet / AAVE", tags: ["criticism", "internet"] },
  { term: "wack", variants: ["whack"], pos: "adj.", gloss: "bad, lame", def: "Of poor quality; disappointing. A foundational hip-hop-era criticism.", example: "Cancelling the show last minute was wack.", origin: "AAVE / early hip-hop", tags: ["criticism"] },
  { term: "trash", variants: [], pos: "adj.", gloss: "terrible", def: "Very bad, worthless. Stronger than mid.", example: "My wifi has been trash all week.", origin: "AAVE / internet", tags: ["criticism"] },
  { term: "basic", variants: [], pos: "adj.", gloss: "unoriginal", def: "Predictably mainstream; lacking individual taste.", example: "A pumpkin spice latte? That's so basic.", origin: "AAVE, mainstreamed via internet", tags: ["criticism"] },
  { term: "cheeks", variants: [], pos: "adj.", gloss: "bad", def: "Of poor quality; disappointing.", example: "That game's servers are cheeks.", origin: "AAVE / gaming internet", tags: ["criticism", "internet"] },
  { term: "brick", variants: [], pos: "adj.", gloss: "freezing cold", def: "(Of weather) very cold. Also, in basketball, a badly missed shot.", example: "It's brick outside, wear a real coat.", origin: "New York", tags: ["ny", "weather"] },

  // ---- people & relationships ----
  { term: "fam", variants: [], pos: "n.", gloss: "close friend(s)", def: "Family — used for close friends who feel like family; also a warm way to address someone.", example: "Good to see you, fam.", origin: "AAVE / UK adoption via grime", tags: ["people"] },
  { term: "bruh", variants: ["bruv"], pos: "n./interj.", gloss: "friend / (exasperation)", def: "Brother/friend as address; also an interjection of disbelief or exasperation. 'Bruv' is the UK equivalent.", example: "Bruh. You did not just say that.", origin: "AAVE ('bruh'); UK/London ('bruv')", tags: ["people", "uk"] },
  { term: "homie", variants: ["homey", "homies"], pos: "n.", gloss: "close friend", def: "A trusted friend, originally someone from your home neighborhood ('homeboy').", example: "I've known that homie since third grade.", origin: "Chicano & Black American communities", tags: ["people"] },
  { term: "og", variants: ["o.g."], pos: "n./adj.", gloss: "original / a respected elder", def: "'Original gangster' historically; now anyone senior, original, or deeply respected in a scene.", example: "She's an OG in the sneaker community.", origin: "Los Angeles, AAVE", tags: ["people", "respect"] },
  { term: "day one", variants: ["day ones", "day 1"], pos: "n.", gloss: "friend from the beginning", def: "Someone who has supported you since the very start.", example: "Marcus is a day one — he believed in the shop before anyone.", origin: "AAVE / hip-hop", tags: ["people", "loyalty"] },
  { term: "ride or die", variants: ["ride-or-die"], pos: "n.", gloss: "unconditionally loyal friend", def: "A person loyal through anything.", example: "That's my ride or die right there.", origin: "AAVE / hip-hop", tags: ["people", "loyalty"] },
  { term: "real one", variants: ["a real one"], pos: "n.", gloss: "genuine, dependable person", def: "Someone authentic and dependable.", example: "You stayed to help clean up? A real one.", origin: "AAVE", tags: ["people", "respect"] },
  { term: "squad", variants: [], pos: "n.", gloss: "friend group", def: "Your close circle of friends.", example: "Whole squad's coming to the cookout.", origin: "AAVE / hip-hop", tags: ["people"] },
  { term: "mandem", variants: [], pos: "n.", gloss: "the guys / friend group", def: "One's group of (male) friends.", example: "Linking up with the mandem this weekend.", origin: "UK — London Multicultural English, via Jamaican Patois", tags: ["people", "uk"] },
  { term: "opp", variants: ["opps", "ops"], pos: "n.", gloss: "opponent, rival", def: "Opposition — a rival or enemy; used loosely for anyone working against you.", example: "Don't share the plan, there might be opps in the group chat.", origin: "Chicago drill / AAVE", tags: ["people", "conflict"] },
  { term: "simp", variants: ["simping"], pos: "n./v.", gloss: "someone excessively eager to please a crush", def: "A person who goes overboard doing things for someone they're attracted to. Often used teasingly.", example: "He drove two hours to bring her soup — okay, simp.", origin: "AAVE (decades old), revived by internet", tags: ["people", "internet"] },
  { term: "stan", variants: ["stanning"], pos: "n./v.", gloss: "obsessive fan / to be a devoted fan", def: "An extremely devoted fan; to stan is to support enthusiastically. From Eminem's 2000 song 'Stan'.", example: "I stan that author — I've read everything twice.", origin: "Hip-hop (Eminem) / internet fandom", tags: ["people", "internet"] },
  { term: "snack", variants: [], pos: "n.", gloss: "attractive person", def: "A very attractive person.", example: "Your date is a whole snack.", origin: "AAVE", tags: ["people"] },
  { term: "thirsty", variants: ["thirst"], pos: "adj.", gloss: "desperate for attention", def: "Too eager for attention or approval, especially romantic.", example: "Liking every single photo in a row is a little thirsty.", origin: "AAVE", tags: ["people", "criticism"] },
  { term: "npc", variants: [], pos: "n.", gloss: "person on autopilot", def: "'Non-player character' — teasing label for someone acting scripted or without originality.", example: "He gives the same three answers every time, total NPC energy.", origin: "Gaming / internet", tags: ["people", "internet"] },
  { term: "main character", variants: ["main character energy"], pos: "n.", gloss: "person living boldly, center-stage", def: "Someone living like the protagonist of their own story; can be admiring or gently mocking.", example: "She wore a gown to the grocery store — main character energy.", origin: "Internet (TikTok era)", tags: ["people", "internet"] },
  { term: "wasteman", variants: [], pos: "n.", gloss: "worthless, unreliable person", def: "A person who wastes time and potential; a strong dismissal.", example: "He borrowed the ladder in March and it's still gone — wasteman.", origin: "UK — London, via Jamaican Patois", tags: ["people", "uk", "criticism"] },
  { term: "roadman", variants: [], pos: "n.", gloss: "street-savvy young man (UK)", def: "A young man deeply of UK street culture — the slang, the tracksuits, the postcode knowledge. Tone ranges from neutral description to stereotype; use with awareness.", example: "He talks like a roadman but he's from a quiet suburb.", origin: "UK — London", tags: ["people", "uk"] },

  // ---- money & possessions ----
  { term: "bread", variants: [], pos: "n.", gloss: "money", def: "Money. 'Let's get this bread' = let's go earn.", example: "Working doubles all week for that bread.", origin: "AAVE (with older jazz-era roots)", tags: ["money"] },
  { term: "bag", variants: ["the bag", "secure the bag"], pos: "n.", gloss: "a large sum of money", def: "Money, especially a big payment or opportunity. 'Secure the bag' = make sure you get paid.", example: "She signed the deal — secured the bag.", origin: "AAVE / hip-hop", tags: ["money"] },
  { term: "guap", variants: [], pos: "n.", gloss: "a lot of money", def: "A large amount of money.", example: "That side business is bringing in guap.", origin: "AAVE / hip-hop", tags: ["money"] },
  { term: "racks", variants: ["rack"], pos: "n.", gloss: "thousands of dollars", def: "A rack is a thousand dollars; racks means serious money.", example: "New transmission cost me two racks.", origin: "AAVE / hip-hop", tags: ["money"] },
  { term: "bands", variants: [], pos: "n.", gloss: "bundles of cash", def: "Stacks of money, from the rubber bands around them.", example: "Saving bands for the down payment.", origin: "AAVE / hip-hop", tags: ["money"] },
  { term: "cheddar", variants: ["cheese"], pos: "n.", gloss: "money", def: "Money.", example: "That overtime is extra cheddar.", origin: "AAVE", tags: ["money"] },
  { term: "cop", variants: ["copped"], pos: "v.", gloss: "buy, obtain", def: "To acquire or purchase something.", example: "I copped those tickets the second they dropped.", origin: "AAVE", tags: ["money", "shopping"] },
  { term: "flex", variants: ["flexing", "flexin"], pos: "v./n.", gloss: "show off / a show of wealth", def: "To show off possessions, achievements, or status; a 'flex' is the thing shown off. 'Weird flex but ok' mocks an odd boast.", example: "Posting your gym stats every day is a flex.", origin: "AAVE / hip-hop", tags: ["money", "style"] },
  { term: "ice", variants: ["iced out"], pos: "n.", gloss: "diamond jewelry", def: "Diamonds or flashy jewelry; 'iced out' = covered in it.", example: "His watch is pure ice.", origin: "AAVE / hip-hop", tags: ["money", "style"] },
  { term: "whip", variants: [], pos: "n.", gloss: "car", def: "A car, especially a nice one.", example: "Clean whip — is it new?", origin: "AAVE / hip-hop", tags: ["things"] },
  { term: "crib", variants: [], pos: "n.", gloss: "home", def: "One's home or apartment.", example: "Movie night at my crib on Friday.", origin: "AAVE (long-established)", tags: ["things"] },
  { term: "plug", variants: ["the plug"], pos: "n.", gloss: "a connection / supplier", def: "A person who can get you something hard to find — tickets, deals, goods. Originally a supplier connection.", example: "She's my plug for concert tickets.", origin: "AAVE / Atlanta hip-hop", tags: ["people", "money"] },
  { term: "come up", variants: ["come-up", "came up"], pos: "n./v.", gloss: "a lucky gain / rise in status", def: "A stroke of good fortune or a rise from humble beginnings. 'That's a come up' = great find.", example: "Found this jacket for $5 at the thrift — huge come up.", origin: "AAVE", tags: ["money", "success"] },
  { term: "glow up", variants: ["glow-up", "glowed up"], pos: "n./v.", gloss: "impressive transformation", def: "A dramatic improvement in looks, confidence, or life situation over time.", example: "Check the graduation photos — what a glow up.", origin: "AAVE / hip-hop (Chief Keef popularized)", tags: ["success"] },

  // ---- feelings & reactions ----
  { term: "salty", variants: [], pos: "adj.", gloss: "bitter, resentful", def: "Annoyed or resentful, usually about something minor; a sore loser's mood.", example: "He's still salty about losing at spades.", origin: "AAVE", tags: ["feelings"] },
  { term: "pressed", variants: [], pos: "adj.", gloss: "upset, obsessed over something", def: "Visibly bothered and unable to let something go.", example: "Why are you so pressed about my haircut?", origin: "AAVE", tags: ["feelings"] },
  { term: "big mad", variants: [], pos: "adj.", gloss: "extremely angry", def: "Very angry — with a hint that the anger is disproportionate.", example: "He got big mad over a board game.", origin: "AAVE", tags: ["feelings"] },
  { term: "shook", variants: [], pos: "adj.", gloss: "shocked, rattled", def: "Deeply startled or unsettled.", example: "The ending of that show left me shook.", origin: "AAVE / '90s hip-hop (Mobb Deep)", tags: ["feelings"] },
  { term: "tight", variants: [], pos: "adj.", gloss: "upset / (older) excellent", def: "Angry or annoyed ('I'm tight'). In older usage: cool or excellent — context decides.", example: "I was tight when they cancelled the flight.", origin: "AAVE / NY", tags: ["feelings", "ny"] },
  { term: "in my feelings", variants: ["in my feels", "in their feelings"], pos: "phrase", gloss: "emotionally affected", def: "Overcome by emotion — often wistful, hurt, or sentimental.", example: "That song has me in my feelings.", origin: "AAVE", tags: ["feelings"] },
  { term: "vibe", variants: ["vibes", "vibing", "vibin"], pos: "n./v.", gloss: "atmosphere / to relax and enjoy", def: "The feeling or atmosphere of a person, place, or moment; to vibe is to relax and enjoy, or to click with someone. 'It's a vibe' = the atmosphere is great.", example: "This coffee shop is a whole vibe.", origin: "AAVE (from jazz-era 'vibrations')", tags: ["feelings"] },
  { term: "mood", variants: ["big mood"], pos: "n./interj.", gloss: "extremely relatable", def: "Said of something that captures exactly how you feel.", example: "A nap at 2pm on Sunday? Mood.", origin: "Internet / AAVE", tags: ["feelings", "internet"] },
  { term: "hype", variants: ["hyped"], pos: "n./adj.", gloss: "excitement / excited", def: "Intense excitement or promotion; hyped = very excited.", example: "I'm so hyped for the season finale.", origin: "AAVE / hip-hop", tags: ["feelings"] },
  { term: "turnt", variants: ["turn up", "turnt up"], pos: "adj./v.", gloss: "wildly energetic / to party hard", def: "In high-energy party mode. 'Turn up!' is a call to celebrate.", example: "The crowd was turnt by the second song.", origin: "AAVE / Southern hip-hop", tags: ["feelings", "party"] },
  { term: "wildin", variants: ["wildin'", "wilding", "wylin", "wylin'"], pos: "v.", gloss: "acting outrageously", def: "Behaving in a wild, reckless, or absurd way; also 'you're wildin' = you're out of line or exaggerating.", example: "Fifty dollars for parking? They're wildin.", origin: "New York, AAVE", tags: ["feelings", "ny"] },
  { term: "no chill", variants: ["zero chill"], pos: "phrase", gloss: "no restraint", def: "Lacking self-restraint or moderation.", example: "She has no chill when it comes to trivia night.", origin: "AAVE / internet", tags: ["feelings"] },
  { term: "savage", variants: [], pos: "adj.", gloss: "brutally bold", def: "Fearlessly blunt or ruthless, usually admiringly.", example: "She read the whole email aloud in the meeting — savage.", origin: "AAVE / hip-hop", tags: ["praise"] },
  { term: "extra", variants: [], pos: "adj.", gloss: "over the top", def: "Excessively dramatic; doing far more than the situation calls for.", example: "A smoke machine at a birthday dinner is extra.", origin: "AAVE", tags: ["criticism"] },
  { term: "sus", variants: ["suss"], pos: "adj.", gloss: "suspicious", def: "Suspicious or questionable; giving reason for doubt. Predates but was super-charged by the game Among Us.", example: "He left right before the bill came — sus.", origin: "AAVE / policing-era 'suspect', internet-revived", tags: ["criticism", "internet"] },

  // ---- talk, drama & the internet ----
  { term: "tea", variants: ["the tea", "spill the tea"], pos: "n.", gloss: "gossip", def: "Juicy news or gossip; to 'spill the tea' is to share it.", example: "Okay, spill the tea — what happened at the reunion?", origin: "Black drag culture ('T' for truth)", tags: ["talk"] },
  { term: "shade", variants: ["throwing shade", "shady"], pos: "n.", gloss: "a subtle insult", def: "Indirect, artful disrespect. 'Throwing shade' = insulting without saying it outright.", example: "Saying 'it's brave to wear that' is pure shade.", origin: "Ballroom culture (Paris Is Burning era)", tags: ["talk", "conflict"] },
  { term: "clap back", variants: ["clapback", "clapped back"], pos: "n./v.", gloss: "a sharp comeback", def: "A quick, cutting response to criticism.", example: "Her clap back in the comments was flawless.", origin: "AAVE / hip-hop (Ja Rule popularized)", tags: ["talk", "conflict"] },
  { term: "dragged", variants: ["drag", "dragging"], pos: "v.", gloss: "harshly criticized", def: "To be publicly and thoroughly criticized, especially online.", example: "The airline got dragged for that policy.", origin: "AAVE / internet", tags: ["talk", "internet"] },
  { term: "ratio", variants: ["ratioed"], pos: "n./v.", gloss: "out-liked rebuttal", def: "When a reply gets more likes than the post it criticizes — a scoreboard of public disagreement.", example: "His hot take got ratioed within an hour.", origin: "Twitter/X culture", tags: ["internet"] },
  { term: "receipts", variants: [], pos: "n.", gloss: "proof", def: "Evidence — screenshots, messages, records — backing up a claim.", example: "She kept receipts, so the argument was over fast.", origin: "AAVE (Whitney Houston interview popularized)", tags: ["talk"] },
  { term: "cancelled", variants: ["canceled", "cancel"], pos: "v./adj.", gloss: "publicly boycotted", def: "Withdrawn support from a person, usually over conduct; ranges from serious accountability to jokes ('you're cancelled' among friends).", example: "He put pineapple AND ketchup on pizza. Cancelled.", origin: "AAVE / internet", tags: ["internet", "talk"] },
  { term: "rent free", variants: ["rent-free"], pos: "phrase", gloss: "occupying your thoughts constantly", def: "Living 'rent free in your head' — you can't stop thinking about it.", example: "That embarrassing text lives rent free in my head.", origin: "Internet (older advice-column coinage)", tags: ["internet", "feelings"] },
  { term: "iykyk", variants: ["if you know you know"], pos: "phrase", gloss: "insiders will understand", def: "'If you know, you know' — a nod to those in on the reference.", example: "Back booth at Rosie's Diner. IYKYK.", origin: "Internet / AAVE", tags: ["internet"] },
  { term: "ghost", variants: ["ghosted", "ghosting"], pos: "v.", gloss: "cut off contact suddenly", def: "To disappear from communication without explanation.", example: "We had two great dates, then he ghosted.", origin: "Internet-era dating, AAVE roots", tags: ["people", "internet"] },
  { term: "sleep on", variants: ["slept on", "sleeping on"], pos: "v.", gloss: "underestimate", def: "To overlook or undervalue someone or something. 'Slept on' = underrated.", example: "Don't sleep on the new intern — she's sharp.", origin: "AAVE / hip-hop", tags: ["talk"] },
  { term: "put on", variants: ["put me on", "put you on"], pos: "v.", gloss: "introduce someone to something good", def: "To share a discovery or opportunity with someone; to plug them in.", example: "Let me put you on to this bakery.", origin: "AAVE", tags: ["talk"] },
  { term: "run it back", variants: ["run that back"], pos: "phrase", gloss: "do it again / replay it", def: "Repeat something great — replay the song, rematch the game.", example: "That was too fun. Run it back.", origin: "AAVE / gaming & sports", tags: ["talk"] },
  { term: "cook", variants: ["let him cook", "let her cook", "let them cook", "cooking"], pos: "v.", gloss: "perform impressively (don't interrupt)", def: "To be doing something impressively well. 'Let him cook' = don't interrupt someone on a roll.", example: "Her plan sounds wild but let her cook.", origin: "AAVE / hip-hop & sports media", tags: ["praise"] },
  { term: "rizz", variants: ["rizzed"], pos: "n./v.", gloss: "charisma, charm", def: "Romantic charisma — skill at charming people. Shortened from 'charisma'; popularized by streamer Kai Cenat.", example: "He asked for her number in front of everyone — unmatched rizz.", origin: "AAVE / internet (NYC streaming culture)", tags: ["people", "internet"] },
  { term: "finesse", variants: ["finessed"], pos: "v.", gloss: "cleverly maneuver / talk your way into", def: "To get something through charm, skill, or clever angles — sometimes shading into trickery.", example: "She finessed free upgrades for the whole table.", origin: "AAVE", tags: ["talk"] },
  { term: "delulu", variants: [], pos: "adj.", gloss: "delusional (playfully)", def: "Playfully delusional — indulging an unrealistic hope. 'Delulu is the solulu' jokes that delusion is the solution.", example: "I applied to one job and started planning the celebration. A little delulu.", origin: "K-pop fandom internet", tags: ["internet", "feelings"] },

  // ---- movement & plans ----
  { term: "pull up", variants: ["pull-up", "pulled up"], pos: "v.", gloss: "come over / show up", def: "To arrive somewhere, often on invitation ('pull up!'). Can carry confrontational weight in other contexts.", example: "We're at the court till 8, pull up.", origin: "AAVE", tags: ["plans"] },
  { term: "slide", variants: ["slide through", "slid"], pos: "v.", gloss: "come by", def: "To come over or drop by casually. ('Slide into DMs' = message someone smoothly.)", example: "Slide through after work, we're grilling.", origin: "AAVE", tags: ["plans"] },
  { term: "link", variants: ["link up", "linking"], pos: "v.", gloss: "meet up", def: "To meet up with someone.", example: "Let's link Saturday and plan the trip.", origin: "AAVE / UK", tags: ["plans", "uk"] },
  { term: "dip", variants: ["dipped"], pos: "v.", gloss: "leave", def: "To leave, often quickly or quietly.", example: "This party's dead, let's dip.", origin: "AAVE", tags: ["plans"] },
  { term: "bounce", variants: [], pos: "v.", gloss: "leave", def: "To depart.", example: "I gotta bounce, early shift tomorrow.", origin: "AAVE", tags: ["plans"] },
  { term: "posted", variants: ["posted up"], pos: "v.", gloss: "hanging out in one spot", def: "Settled in one place, relaxing.", example: "We're posted by the food trucks.", origin: "AAVE", tags: ["plans"] },
  { term: "otw", variants: ["on the way"], pos: "phrase", gloss: "on the way", def: "Abbreviation: on the way.", example: "OTW, be there in ten.", origin: "Texting shorthand", tags: ["plans", "internet"] },
  { term: "based", variants: [], pos: "adj.", gloss: "unapologetically yourself", def: "Confidently true to your own views regardless of approval. Coined in this sense by rapper Lil B.", example: "She wore the costume to work anyway. Based.", origin: "Bay Area hip-hop (Lil B), internet-adopted", tags: ["praise", "bay", "internet"] },

  // ---- conflict & caution ----
  { term: "beef", variants: [], pos: "n.", gloss: "an ongoing dispute", def: "A grudge or feud between people or groups.", example: "Those two chefs have had beef since the cook-off.", origin: "AAVE (older American slang roots)", tags: ["conflict"] },
  { term: "smoke", variants: ["want smoke", "no smoke"], pos: "n.", gloss: "conflict, a fight", def: "Trouble or confrontation. 'Want smoke' = looking for a fight; 'no smoke' = no problem with you.", example: "I don't want any smoke, I'm just here for the music.", origin: "AAVE", tags: ["conflict"] },
  { term: "diss", variants: ["dissed", "diss track"], pos: "v./n.", gloss: "insult", def: "To disrespect; a diss track is a song aimed at a rival.", example: "Leaving him off the invite felt like a diss.", origin: "AAVE / hip-hop", tags: ["conflict", "music"] },
  { term: "checked", variants: ["check", "got checked"], pos: "v.", gloss: "corrected firmly", def: "To be firmly corrected or put in your place.", example: "He got checked for talking over the speaker.", origin: "AAVE", tags: ["conflict"] },
  { term: "pipe down", variants: [], pos: "v.", gloss: "quiet down", def: "Stop talking; settle down.", example: "Pipe down, the movie's starting.", origin: "AAVE / general (naval roots)", tags: ["conflict"] },
  { term: "cap it", variants: [], pos: "phrase", gloss: "stop lying", def: "Quit the exaggeration.", example: "Cap it — you did not meet the whole cast.", origin: "AAVE (from cap)", tags: ["truth"] },
  { term: "twelve", variants: ["12"], pos: "n.", gloss: "the police", def: "Slang for police. Origin debated (possibly from the show 'Adam-12' or police radio codes).", example: "Slow down, twelve sits behind that billboard.", origin: "Atlanta / Southern AAVE", tags: ["caution"] },
  { term: "bait", variants: [], pos: "adj.", gloss: "obvious, risky to expose", def: "(UK) Too obvious or well-known; likely to attract unwanted attention.", example: "Don't talk about it on the bus, that's bait.", origin: "UK — London", tags: ["uk", "caution"] },
  { term: "peak", variants: [], pos: "adj.", gloss: "unfortunate (UK)", def: "(UK) Bad luck, harsh, unfair — 'that's peak' sympathizes with misfortune. (US internet sometimes uses 'peak' as 'the best'; context decides.)", example: "Locked out in the rain? That's peak.", origin: "UK — London", tags: ["uk", "feelings"] },

  // ---- UK corner ----
  { term: "innit", variants: [], pos: "interj.", gloss: "isn't it / right?", def: "Contraction of 'isn't it', used as an all-purpose tag seeking agreement.", example: "Long day, innit.", origin: "UK — London Multicultural English", tags: ["uk", "agreement"] },
  { term: "bare", variants: [], pos: "adv.", gloss: "a lot of / very", def: "(UK) Many, much, very.", example: "There were bare people at the market.", origin: "UK — London, via Caribbean English", tags: ["uk", "emphasis"] },
  { term: "peng", variants: [], pos: "adj.", gloss: "very attractive / excellent", def: "(UK) Extremely good-looking or high quality.", example: "That jacket is peng.", origin: "UK — London, via Jamaican Patois", tags: ["uk", "praise"] },
  { term: "ting", variants: [], pos: "n.", gloss: "thing / a romantic interest", def: "(UK) 'Thing'; also a person you're seeing casually.", example: "It's a small ting, don't stress.", origin: "UK / Jamaican Patois", tags: ["uk"] },
  { term: "wagwan", variants: ["wag1"], pos: "interj.", gloss: "what's going on?", def: "Greeting: 'what's going on?'", example: "Wagwan, long time no see.", origin: "Jamaican Patois ('what a gwaan'), UK-adopted", tags: ["uk", "greeting"] },
  { term: "safe", variants: [], pos: "interj.", gloss: "thanks / all good", def: "(UK) Expression of thanks, approval, or goodbye.", example: "'I saved you a seat.' 'Safe.'", origin: "UK — London", tags: ["uk", "agreement"] },
  { term: "allow it", variants: [], pos: "phrase", gloss: "leave it / let it go", def: "(UK) Stop, drop it, let it slide — the opposite of what 'allow' suggests.", example: "Allow it, he already apologized.", origin: "UK — London", tags: ["uk"] },
  { term: "ends", variants: ["the ends"], pos: "n.", gloss: "neighborhood", def: "(UK) One's local area.", example: "Best chicken shop in the ends, hands down.", origin: "UK — London", tags: ["uk", "places"] },
  { term: "yard", variants: [], pos: "n.", gloss: "home", def: "Home or house.", example: "Come round my yard after.", origin: "Jamaican Patois, UK-adopted", tags: ["uk", "places"] },
  { term: "jawn", variants: [], pos: "n.", gloss: "thing (any thing)", def: "An all-purpose noun for any object, place, event, or person — famously flexible.", example: "Pass me that jawn on the counter.", origin: "Philadelphia, AAVE", tags: ["places"] },

  // ---- misc essentials ----
  { term: "boujee", variants: ["bougie", "boozhee"], pos: "adj.", gloss: "luxurious / high-maintenance", def: "Aspirationally fancy; enjoying the finer things — from 'bourgeois'. Teasing or admiring by context.", example: "She only drinks sparkling water from glass bottles — boujee.", origin: "AAVE (via French 'bourgeois'; Migos popularized)", tags: ["style", "money"] },
  { term: "clout", variants: ["clout chaser"], pos: "n.", gloss: "fame, influence", def: "Attention and influence, especially online. A 'clout chaser' does anything for it.", example: "He only posts hot takes for clout.", origin: "AAVE / Chicago hip-hop", tags: ["internet"] },
  { term: "hypebeast", variants: [], pos: "n.", gloss: "trend-chasing collector", def: "Someone who buys hyped, limited-release fashion mainly because it's hyped.", example: "The line outside the sneaker shop was all hypebeasts.", origin: "Streetwear culture", tags: ["style", "people"] },
  { term: "grind", variants: ["grinding", "on my grind"], pos: "n./v.", gloss: "hard, persistent work", def: "Relentless effort toward a goal; the daily hustle.", example: "She's been on her grind all semester.", origin: "AAVE / hip-hop", tags: ["success"] },
  { term: "hustle", variants: ["side hustle"], pos: "n./v.", gloss: "ambitious work / a side job", def: "Determined effort to earn; a 'side hustle' is an extra income project.", example: "The candle business started as a side hustle.", origin: "AAVE (older American slang roots)", tags: ["success", "money"] },
  { term: "level up", variants: ["leveled up", "levelled up"], pos: "v.", gloss: "improve your situation", def: "To advance to a better version of your life, skills, or status.", example: "New certification, new job — she leveled up.", origin: "Gaming, AAVE-popularized", tags: ["success"] },
  { term: "w", variants: ["dub", "big w"], pos: "n.", gloss: "a win", def: "A win or success ('take the W'). 'Dub' is the spoken form of the letter W.", example: "Free parking downtown? That's a W.", origin: "Sports / AAVE / internet", tags: ["success", "internet"] },
  { term: "l", variants: ["take the l", "big l"], pos: "n.", gloss: "a loss", def: "A loss, failure, or embarrassment ('took an L').", example: "Wore white to a barbecue — took an L immediately.", origin: "Sports / AAVE / internet", tags: ["internet"] },
  { term: "ratio'd", variants: [], pos: "v.", gloss: "publicly out-voted", def: "See ratio — decisively out-liked by a critical reply.", example: "The brand account got ratio'd by its own customers.", origin: "Twitter/X culture", tags: ["internet"] },
  { term: "fr", variants: ["fr fr", "for real"], pos: "adv.", gloss: "genuinely", def: "'For real' — sincerely, truly. Doubling it ('fr fr') adds emphasis.", example: "That documentary was moving, fr.", origin: "AAVE / texting", tags: ["truth", "internet"] },
  { term: "ngl", variants: ["not gonna lie", "not gon lie"], pos: "phrase", gloss: "honestly", def: "'Not gonna lie' — prefaces an honest admission.", example: "Ngl, I cried at the wedding.", origin: "AAVE / texting", tags: ["truth", "internet"] },
  { term: "tbh", variants: [], pos: "phrase", gloss: "to be honest", def: "'To be honest' — prefaces a frank opinion.", example: "Tbh the original was better.", origin: "Texting shorthand", tags: ["internet"] },
  { term: "imo", variants: ["imho"], pos: "phrase", gloss: "in my opinion", def: "'In my (humble) opinion'.", example: "Best slice in town, imo.", origin: "Internet shorthand", tags: ["internet"] },
  { term: "smh", variants: [], pos: "phrase", gloss: "shaking my head", def: "'Shaking my head' — disappointment or disbelief.", example: "They cancelled the bus route again, smh.", origin: "Internet shorthand", tags: ["internet"] },
  { term: "istg", variants: [], pos: "phrase", gloss: "I swear to god", def: "'I swear to god' — exasperated emphasis.", example: "Istg if this printer jams one more time...", origin: "Texting shorthand", tags: ["internet"] },
];

// Export for Node-based testing without affecting browser usage.
if (typeof module !== "undefined" && module.exports) {
  module.exports = { DICTIONARY };
}
